<a href="https://colab.research.google.com/github/yashczoor/PythonDS/blob/main/1_NumPy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [2]:
import numpy as np
np.__version__

'1.18.5'

In [6]:
import pprint

In [11]:
x = np.array([1,3])

In [13]:
for i in x:
  print(i)

1
3


In [14]:
type(x)

numpy.ndarray

In [15]:
x.ndim

1

In [16]:
x.shape

(2,)

In [17]:
x.size

2

In [18]:
x.dtype

dtype('int64')

In [19]:
#właściwości arraya. Jest jednego typu. Shape i dtype przydatne

In [21]:
x = np.array([1.3,2.3,3.3])

In [22]:
print(x)

[1.3 2.3 3.3]


In [23]:
x.dtype

dtype('float64')

### 2D Array

In [4]:
import numpy as np
x = np.array([[1,2],[-3,1]])

In [5]:
x

array([[ 1,  2],
       [-3,  1]])

In [6]:
x.ndim

2

In [7]:
x.shape

(2, 2)

In [8]:
x.dtype

dtype('int64')

In [9]:
x = np.array([[1,2,4],[4,2,1]])

In [10]:
x

array([[1, 2, 4],
       [4, 2, 1]])

In [11]:
x.shape

(2, 3)

### 3D Array

In [22]:
x = np.array(
    [[[4,3,1],
    [3,1,2]],

     [[4,1,3],[4,2,1]],

     [[3,2,1],
      [4,3,2]]
    ]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [23]:
x.ndim

3

In [24]:
x.shape

(3, 2, 3)

### Data types

In [25]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [26]:
B = np.array([1.0,2.3,4.5])
B.dtype

dtype('float64')

In [28]:
A = np.array([1,2,3], dtype='float')
A.dtype

dtype('float64')

In [29]:
A = np.array([1,2,3],dtype='complex') #liczby złożone
A.dtype

dtype('complex128')

In [32]:
A = np.array([1.5,2.7,3.1],dtype = 'int')
A.dtype

dtype('int64')

In [33]:
print(A)

[1 2 3]


In [34]:
A = np.array([True, False])

In [35]:
A

array([ True, False])

In [36]:
A.dtype

dtype('bool')

In [37]:
A = np.array([24,120,230], dtype=np.int8)
A.dtype #mogę podać taki typ, żeby ograniczyć ilość zajmowanego miejsca

dtype('int8')

In [38]:
A = np.array([24,120,230], dtype=np.uint8)
A.dtype #mogę podać taki typ, żeby ograniczyć ilość zajmowanego miejsca

dtype('uint8')

###Tworzenie tablic

In [39]:
  np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [41]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
np.ones(shape=(5,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [46]:
np.full(shape=(3,3),fill_value=7,dtype='int')

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])