<a href="https://colab.research.google.com/github/yashczoor/PythonDS/blob/main/1_NumPy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [2]:
import numpy as np
np.__version__

'1.18.5'

In [6]:
import pprint

In [11]:
x = np.array([1,3])

In [13]:
for i in x:
  print(i)

1
3


In [14]:
type(x)

numpy.ndarray

In [15]:
x.ndim

1

In [16]:
x.shape

(2,)

In [17]:
x.size

2

In [18]:
x.dtype

dtype('int64')

In [19]:
#właściwości arraya. Jest jednego typu. Shape i dtype przydatne

In [21]:
x = np.array([1.3,2.3,3.3])

In [22]:
print(x)

[1.3 2.3 3.3]


In [23]:
x.dtype

dtype('float64')

### 2D Array

In [4]:
import numpy as np
x = np.array([[1,2],[-3,1]])

In [5]:
x

array([[ 1,  2],
       [-3,  1]])

In [6]:
x.ndim

2

In [7]:
x.shape

(2, 2)

In [8]:
x.dtype

dtype('int64')

In [9]:
x = np.array([[1,2,4],[4,2,1]])

In [10]:
x

array([[1, 2, 4],
       [4, 2, 1]])

In [11]:
x.shape

(2, 3)

### 3D Array

In [22]:
x = np.array(
    [[[4,3,1],
    [3,1,2]],

     [[4,1,3],[4,2,1]],

     [[3,2,1],
      [4,3,2]]
    ]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [23]:
x.ndim

3

In [24]:
x.shape

(3, 2, 3)

### Data types

In [25]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [26]:
B = np.array([1.0,2.3,4.5])
B.dtype

dtype('float64')

In [28]:
A = np.array([1,2,3], dtype='float')
A.dtype

dtype('float64')

In [29]:
A = np.array([1,2,3],dtype='complex') #liczby złożone
A.dtype

dtype('complex128')

In [32]:
A = np.array([1.5,2.7,3.1],dtype = 'int')
A.dtype

dtype('int64')

In [33]:
print(A)

[1 2 3]


In [34]:
A = np.array([True, False])

In [35]:
A

array([ True, False])

In [36]:
A.dtype

dtype('bool')

In [37]:
A = np.array([24,120,230], dtype=np.int8)
A.dtype #mogę podać taki typ, żeby ograniczyć ilość zajmowanego miejsca

dtype('int8')

In [38]:
A = np.array([24,120,230], dtype=np.uint8)
A.dtype #mogę podać taki typ, żeby ograniczyć ilość zajmowanego miejsca

dtype('uint8')

###Tworzenie tablic

In [39]:
  np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [41]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [42]:
np.ones(shape=(5,5),dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [46]:
np.full(shape=(3,3),fill_value=7,dtype='int')

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [48]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(1,3)

array([1, 2])

In [51]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [53]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [55]:
np.arange(start=10,stop=100,step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [57]:
np.arange(start=1000,stop=99,step=-10)

array([1000,  990,  980,  970,  960,  950,  940,  930,  920,  910,  900,
        890,  880,  870,  860,  850,  840,  830,  820,  810,  800,  790,
        780,  770,  760,  750,  740,  730,  720,  710,  700,  690,  680,
        670,  660,  650,  640,  630,  620,  610,  600,  590,  580,  570,
        560,  550,  540,  530,  520,  510,  500,  490,  480,  470,  460,
        450,  440,  430,  420,  410,  400,  390,  380,  370,  360,  350,
        340,  330,  320,  310,  300,  290,  280,  270,  260,  250,  240,
        230,  220,  210,  200,  190,  180,  170,  160,  150,  140,  130,
        120,  110,  100])

In [59]:
np.arange(start=0,stop=1,step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [61]:
np.linspace(start=0,stop=1,num=11) #ile elementów z przedziału chcę wygenerować

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [62]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [63]:
A.shape

(15,)

In [67]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [68]:
A.reshape((3,-1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [69]:
#-1 oznacza dobierz odpowiednio ten rozmiar

In [70]:
A.reshape((-1,3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [71]:
A.reshape((3,5,1))

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]]])

###Podstawowe operacje na tablicach

In [78]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [79]:
A + B

array([6, 0, 7, 4])

In [75]:
#dodaje element po elemencie

In [80]:
A - B

array([0, 2, 1, 0])

In [81]:
A * B

array([ 9, -1, 12,  4])

In [85]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [86]:
A + 3

array([6, 4, 7, 5])

In [87]:
A += 1

In [88]:
A

array([4, 2, 5, 3])

In [89]:
A -= 1

In [90]:
2 * A
A

array([3, 1, 4, 2])

In [91]:
A + 3*B

array([12, -2, 13,  8])

In [92]:
np.add(A,B)

array([6, 0, 7, 4])

In [93]:
np.subtract(A,B)

array([0, 2, 1, 0])

In [94]:
np.multiply(A,B)

array([ 9, -1, 12,  4])

In [95]:
np.divide(A,B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [98]:
 X = np.array([[1,3],[-2,0]])
 Y = np.array([[6,0],[-1,2]])

In [99]:
print(X)
print('\n')
print(Y)

[[ 1  3]
 [-2  0]]


[[ 6  0]
 [-1  2]]


In [100]:
X * Y

array([[6, 0],
       [2, 0]])

In [101]:
#mnożenie macierzy:

In [103]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [104]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [105]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [106]:
X @ Y

array([[  3,   6],
       [-12,   0]])

###Generowanie liczb pseudolosowych

In [108]:
np.random.seed(0)

In [110]:
np.random.randn()

0.4001572083672233

In [111]:
np.random.randn(10)

array([ 0.97873798,  2.2408932 ,  1.86755799, -0.97727788,  0.95008842,
       -0.15135721, -0.10321885,  0.4105985 ,  0.14404357,  1.45427351])

In [112]:
np.random.randn(10,4)

array([[ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275],
       [-1.04855297, -1.42001794, -1.70627019,  1.9507754 ],
       [-0.50965218, -0.4380743 , -1.25279536,  0.77749036],
       [-1.61389785, -0.21274028, -0.89546656,  0.3869025 ]])

In [113]:
np.random.rand()

0.1965823616800535

In [114]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [115]:
np.random.rand(10,4)

array([[0.03918779, 0.28280696, 0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318, 0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145, 0.26538949, 0.52324805],
       [0.09394051, 0.5759465 , 0.9292962 , 0.31856895],
       [0.66741038, 0.13179786, 0.7163272 , 0.28940609],
       [0.18319136, 0.58651293, 0.02010755, 0.82894003],
       [0.00469548, 0.67781654, 0.27000797, 0.73519402],
       [0.96218855, 0.24875314, 0.57615733, 0.59204193],
       [0.57225191, 0.22308163, 0.95274901, 0.44712538],
       [0.84640867, 0.69947928, 0.29743695, 0.81379782]])

In [116]:
np.random.randint(10)

8

In [119]:
np.random.randint(10)

5

In [120]:
np.random.randint(low=10, high=101)

35

In [121]:
np.random.randint(low=10,high=101,size=10)

array([90, 70, 71, 93, 43, 42, 80, 95, 41, 23])

In [122]:
np.random.choice([4,2,1,3])

3

In [123]:
#wybiera losowy element z podanej listy

In [126]:
np.random.choice(['boo','foo','bar','spam'])

'spam'

In [127]:
data = np.arange(10)

In [128]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
np.random.shuffle(data)

In [130]:
data

array([5, 7, 8, 4, 1, 3, 6, 0, 2, 9])

In [131]:
data.sort()

In [132]:
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###Podstawowe funkcje w numpy

In [133]:
np.exp(1)

2.718281828459045

In [134]:
#stała Heullera

In [135]:
np.exp(2)

7.38905609893065

In [136]:
np.sqrt(9)

3.0

In [137]:
np.all([2,3,1])

True

In [138]:
np.all([2==2,1>=1])

True

In [139]:
np.all([1,-1])

True

In [140]:
np.all([1,0])

False

In [141]:
#all jak oraz

In [142]:
np.any([0,0,1])

True

In [143]:
np.any([0,0])

False

In [144]:
#jak LUB

In [145]:
bool(0)

False

In [146]:
bool(1)

True

In [147]:
bool('a')

True

In [149]:
A = np.random.rand(5)
A

array([0.35231166, 0.46924917, 0.84114013, 0.90464774, 0.03755938])

In [150]:
np.argmax(A)

3

In [151]:
#numer największego argumentu tablicy

In [152]:
A[np.argmax(A)]

0.9046477442095134

In [153]:
A[np.argmin(A)]

0.03755938382814028

In [154]:
np.argsort(A)

array([4, 0, 1, 2, 3])

In [155]:
A

array([0.35231166, 0.46924917, 0.84114013, 0.90464774, 0.03755938])

In [156]:
#zwraca ranking elementów

In [157]:
np.max(A)

0.9046477442095134

In [158]:
np.min(A)

0.03755938382814028

In [159]:
np.average(A)

0.5209816186028057

In [160]:
np.mean(A)

0.5209816186028057

In [161]:
np.median(A)

0.46924917399024213

In [162]:
np.std(A)

0.3207877883121654

###indeksowanie i wycinanie tablic

In [163]:
A = np.arange(20)

In [164]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [165]:
#A[id], A[start:stop], A[start:], A[:stop]

In [166]:
A[2]

2

In [168]:
A|[0]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [169]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [170]:
A[:2]

array([0, 1])

In [171]:
A[[0,2]]

array([0, 2])

In [172]:
#lista indeksów, które indeksy wyciąć

In [173]:
A[-1]

19

In [174]:
#zwróci ostatni element

In [175]:
A[10:15]

array([10, 11, 12, 13, 14])

In [177]:
A = A.reshape(4,5)

In [178]:
A 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [179]:
A[0]

array([0, 1, 2, 3, 4])

In [180]:
A[1]

array([5, 6, 7, 8, 9])

In [181]:
A[:,0] #ZWRACA KOLUMNĘ

array([ 0,  5, 10, 15])

In [182]:
A[:,-2] #PRZEDOSTATNIA KOLUMNA

array([ 3,  8, 13, 18])

In [183]:
A[1,1]

6

In [184]:
A[2,3]#WIERSZ, KOLUMNA

13

In [186]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [187]:
A[1,2] = 14

In [189]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [190]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [191]:
for row in A:
  print(row[0])

0
5
10
15


In [192]:
for row in A:
  for col in row:
    print(col)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [193]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [194]:
A.shape()

TypeError: ignored

In [195]:
A.shape

(4, 5)

In [196]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [197]:
A.ravel

<function ndarray.ravel>

In [198]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [199]:
A.shape

(4, 5)

In [200]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [201]:
A = np.arange(-10,10,0.5)

In [203]:
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [204]:
A.reshape(10,-1)

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [205]:
A > 0

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [206]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [208]:
A[A > -5 and A < 5]

ValueError: ignored

In [209]:
np.bitwise_and(A>-5,A<5)

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False])

In [210]:
np.bitwise_or(A<-5,A>5)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True])